test-pack

diff --git a/.github/workflows/push_update.yml b/.github/workflows/push_update.yml
--- a/.github/workflows/push_update.yml
+++ b/.github/workflows/push_update.yml
@@ -50,6 +50,10 @@ jobs:
           cd core
           cmake -S . -B build
           cmake --build build
+          if [ $? -ne 0 ]; then
+            echo "❌ Build failed!"
+            exit 1
+          fi
           ./build/core_test
           
       - name: Upload Artifact
